apiVersion: v2
name: haven-redis
description: Haven Platform managed Redis chart (OpsTree Redis Operator)
type: application
version: 0.1.0
appVersion: "7.0"
keywords:
  - haven
  - redis
  - opstree
  - cache
maintainers:
  - name: Haven Platform Team
