"""Tests for service dependencies in app creation (Phase 2A).

Covers:
  - RequestedServiceSpec schema validation
  - ApplicationCreate with requested_services field
  - pending_services model column
  - Auto-connect logic (_auto_connect_pending_services)
  - GET /apps/{slug}/services endpoint
"""

from __future__ import annotations

import types
import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.models.managed_service import ServiceStatus, ServiceTier, ServiceType
from app.schemas.application import ApplicationCreate, RequestedServiceSpec


# ---------------------------------------------------------------------------
# Schema Tests
# ---------------------------------------------------------------------------


class TestRequestedServiceSpec:
    def test_valid_postgres(self):
        spec = RequestedServiceSpec(service_type="postgres")
        assert spec.service_type == "postgres"
        assert spec.tier == "dev"
        assert spec.name is None

    def test_valid_redis_with_name(self):
        spec = RequestedServiceSpec(service_type="redis", name="my-cache", tier="prod")
        assert spec.service_type == "redis"
        assert spec.name == "my-cache"
        assert spec.tier == "prod"

    def test_valid_all_types(self):
        for stype in ("postgres", "mysql", "mongodb", "redis", "rabbitmq"):
            spec = RequestedServiceSpec(service_type=stype)
            assert spec.service_type == stype

    def test_invalid_service_type(self):
        with pytest.raises(Exception):
            RequestedServiceSpec(service_type="oracle")

    def test_invalid_tier(self):
        with pytest.raises(Exception):
            RequestedServiceSpec(service_type="postgres", tier="enterprise")

    def test_invalid_name_pattern(self):
        with pytest.raises(Exception):
            RequestedServiceSpec(service_type="postgres", name="My DB")


class TestApplicationCreateWithServices:
    def test_no_services_default(self):
        app = ApplicationCreate(name="my-app", repo_url="https://github.com/org/repo")
        assert app.requested_services is None

    def test_with_services(self):
        app = ApplicationCreate(
            name="my-api",
            repo_url="https://github.com/org/repo",
            requested_services=[
                RequestedServiceSpec(service_type="postgres"),
                RequestedServiceSpec(service_type="redis", tier="prod"),
            ],
        )
        assert len(app.requested_services) == 2
        assert app.requested_services[0].service_type == "postgres"
        assert app.requested_services[1].tier == "prod"

    def test_with_empty_services(self):
        app = ApplicationCreate(
            name="my-app",
            repo_url="https://github.com/org/repo",
            requested_services=[],
        )
        assert app.requested_services == []

    def test_service_name_auto_generation_hint(self):
        """Name should be None by default, auto-generated by the router."""
        spec = RequestedServiceSpec(service_type="postgres")
        assert spec.name is None

    def test_service_with_custom_name(self):
        spec = RequestedServiceSpec(service_type="mongodb", name="order-db")
        assert spec.name == "order-db"


# ---------------------------------------------------------------------------
# Model Tests
# ---------------------------------------------------------------------------


class TestApplicationModelPendingServices:
    def test_pending_services_column_exists(self):
        from app.models.application import Application

        assert hasattr(Application, "pending_services")

    def test_pending_services_default_none(self):
        """pending_services should default to None."""
        from sqlalchemy import inspect as sa_inspect

        from app.models.application import Application

        mapper = sa_inspect(Application)
        col = mapper.columns["pending_services"]
        assert col.nullable is True


# ---------------------------------------------------------------------------
# Auto-Connect Logic Tests
# ---------------------------------------------------------------------------


def _make_svc(**kwargs):
    defaults = {
        "id": uuid.uuid4(),
        "tenant_id": uuid.uuid4(),
        "name": "myapp-postgres",
        "service_type": ServiceType.POSTGRES,
        "tier": ServiceTier.DEV,
        "status": ServiceStatus.READY,
        "secret_name": "svc-myapp-postgres",
        "service_namespace": "everest",
        "connection_hint": "postgresql://myapp-postgres@myapp-postgres-rw.everest.svc:5432/myapp",
        "credentials_provisioned": True,
        "error_message": None,
    }
    defaults.update(kwargs)
    return types.SimpleNamespace(**defaults)


def _make_app_ns(**kwargs):
    defaults = {
        "id": uuid.uuid4(),
        "tenant_id": uuid.uuid4(),
        "slug": "my-api",
        "env_from_secrets": None,
        "env_vars": {},
        "pending_services": [{"service_name": "myapp-postgres", "service_type": "postgres"}],
        "image_tag": None,
    }
    defaults.update(kwargs)
    return types.SimpleNamespace(**defaults)


def _make_tenant_ns(**kwargs):
    defaults = {
        "id": uuid.uuid4(),
        "slug": "test-tenant",
        "namespace": "tenant-test-tenant",
    }
    defaults.update(kwargs)
    return types.SimpleNamespace(**defaults)


@pytest.mark.asyncio
async def test_auto_connect_matches_pending_service():
    """When a service becomes READY, matching pending_services entry should be connected."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(tenant_id=tenant.id)
    app = _make_app_ns(tenant_id=tenant.id)

    # Mock DB
    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [app]
    mock_db.execute.return_value = mock_result
    mock_db.commit = AsyncMock()

    await _auto_connect_pending_services(mock_db, svc, tenant)

    # App should now have env_from_secrets with the connected service
    assert app.env_from_secrets is not None
    assert len(app.env_from_secrets) == 1
    assert app.env_from_secrets[0]["service_name"] == "myapp-postgres"
    assert app.env_from_secrets[0]["secret_name"] == "svc-myapp-postgres"
    assert app.env_from_secrets[0]["database_url_key"] == "DATABASE_URL"

    # pending_services should be cleared
    assert app.pending_services is None

    # DATABASE_URL should be injected into env_vars
    assert "DATABASE_URL" in app.env_vars
    assert app.env_vars["DATABASE_URL"].startswith("postgresql://")


@pytest.mark.asyncio
async def test_auto_connect_no_match():
    """When service name doesn't match any pending_services, nothing should change."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(name="other-service", tenant_id=tenant.id)
    app = _make_app_ns(tenant_id=tenant.id)

    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [app]
    mock_db.execute.return_value = mock_result

    await _auto_connect_pending_services(mock_db, svc, tenant)

    # No changes
    assert app.env_from_secrets is None
    assert len(app.pending_services) == 1


@pytest.mark.asyncio
async def test_auto_connect_redis_no_database_url():
    """Redis connection should not inject DATABASE_URL."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(
        name="myapp-redis",
        service_type=ServiceType.REDIS,
        connection_hint="redis://myapp-redis.tenant-test.svc:6379",
        tenant_id=tenant.id,
    )
    app = _make_app_ns(
        tenant_id=tenant.id,
        pending_services=[{"service_name": "myapp-redis", "service_type": "redis"}],
    )

    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [app]
    mock_db.execute.return_value = mock_result
    mock_db.commit = AsyncMock()

    await _auto_connect_pending_services(mock_db, svc, tenant)

    assert app.env_from_secrets is not None
    assert app.env_from_secrets[0]["database_url_key"] is None
    # No DATABASE_URL for Redis
    assert "DATABASE_URL" not in app.env_vars


@pytest.mark.asyncio
async def test_auto_connect_multiple_pending():
    """When app has 2 pending services, connecting one should leave the other pending."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(name="myapp-postgres", tenant_id=tenant.id)
    app = _make_app_ns(
        tenant_id=tenant.id,
        pending_services=[
            {"service_name": "myapp-postgres", "service_type": "postgres"},
            {"service_name": "myapp-redis", "service_type": "redis"},
        ],
    )

    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [app]
    mock_db.execute.return_value = mock_result
    mock_db.commit = AsyncMock()

    await _auto_connect_pending_services(mock_db, svc, tenant)

    # Postgres connected, Redis still pending
    assert len(app.env_from_secrets) == 1
    assert app.env_from_secrets[0]["service_name"] == "myapp-postgres"
    assert len(app.pending_services) == 1
    assert app.pending_services[0]["service_name"] == "myapp-redis"


@pytest.mark.asyncio
async def test_auto_connect_mysql_url_key():
    """MySQL should use MYSQL_URL key."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(
        name="myapp-mysql",
        service_type=ServiceType.MYSQL,
        connection_hint="mysql://user:pass@host:3306/db",
        tenant_id=tenant.id,
    )
    app = _make_app_ns(
        tenant_id=tenant.id,
        pending_services=[{"service_name": "myapp-mysql", "service_type": "mysql"}],
    )

    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [app]
    mock_db.execute.return_value = mock_result
    mock_db.commit = AsyncMock()

    await _auto_connect_pending_services(mock_db, svc, tenant)

    assert app.env_from_secrets[0]["database_url_key"] == "MYSQL_URL"
    assert "MYSQL_URL" in app.env_vars
    assert "DATABASE_URL" in app.env_vars  # Also set as generic alias


@pytest.mark.asyncio
async def test_auto_connect_already_connected():
    """If service is already in env_from_secrets, just clear from pending."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(name="myapp-postgres", tenant_id=tenant.id)
    app = _make_app_ns(
        tenant_id=tenant.id,
        env_from_secrets=[{"service_name": "myapp-postgres", "secret_name": "svc-myapp-postgres"}],
        pending_services=[{"service_name": "myapp-postgres", "service_type": "postgres"}],
    )

    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [app]
    mock_db.execute.return_value = mock_result
    mock_db.commit = AsyncMock()

    await _auto_connect_pending_services(mock_db, svc, tenant)

    # env_from_secrets unchanged (still 1 entry)
    assert len(app.env_from_secrets) == 1
    # pending_services cleared
    assert app.pending_services is None


@pytest.mark.asyncio
async def test_auto_connect_no_apps_with_pending():
    """When no apps have pending_services, nothing should happen."""
    from app.main import _auto_connect_pending_services

    tenant = _make_tenant_ns()
    svc = _make_svc(tenant_id=tenant.id)

    mock_db = AsyncMock()
    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = []  # No apps
    mock_db.execute.return_value = mock_result

    # Should not raise
    await _auto_connect_pending_services(mock_db, svc, tenant)


# ---------------------------------------------------------------------------
# Schema / Response Tests
# ---------------------------------------------------------------------------


class TestApplicationResponsePendingServices:
    def test_response_includes_pending_services(self):
        from app.schemas.application import ApplicationResponse

        fields = ApplicationResponse.model_fields
        assert "pending_services" in fields

    def test_response_pending_services_default_none(self):
        from app.schemas.application import ApplicationResponse

        assert ApplicationResponse.model_fields["pending_services"].default is None


# ---------------------------------------------------------------------------
# Alembic Migration Tests
# ---------------------------------------------------------------------------


def test_alembic_migration_exists():
    """Migration 0021 should exist for pending_services column."""
    from pathlib import Path

    migration = Path("alembic/versions/0021_add_pending_services.py")
    assert migration.exists(), "Migration 0021 not found"


def test_alembic_migration_chain():
    """Migration 0021 should follow 0020."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "migration_0021", "alembic/versions/0021_add_pending_services.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    assert mod.revision == "0021"
    assert mod.down_revision == "0020"


# ---------------------------------------------------------------------------
# Integration-style Tests
# ---------------------------------------------------------------------------


class TestRequestedServicesFlow:
    """Test the full flow of creating an app with requested services."""

    def test_application_create_schema_accepts_requested_services(self):
        """ApplicationCreate should accept the requested_services field."""
        data = {
            "name": "backend-api",
            "repo_url": "https://github.com/org/backend",
            "requested_services": [
                {"service_type": "postgres"},
                {"service_type": "redis", "tier": "prod"},
                {"service_type": "rabbitmq", "name": "event-bus"},
            ],
        }
        app = ApplicationCreate(**data)
        assert len(app.requested_services) == 3
        assert app.requested_services[0].name is None
        assert app.requested_services[1].tier == "prod"
        assert app.requested_services[2].name == "event-bus"

    def test_service_name_auto_generation(self):
        """When name is None, router should generate {app-slug}-{type}."""
        spec = RequestedServiceSpec(service_type="postgres")
        # Simulate what the router does:
        app_slug = "backend-api"
        svc_name = spec.name or f"{app_slug}-{spec.service_type}"
        assert svc_name == "backend-api-postgres"

    def test_three_tier_demo_services(self):
        """Demo scenario: 3-tier app with PG + Redis + RabbitMQ."""
        app = ApplicationCreate(
            name="demo-api",
            repo_url="https://github.com/org/demo",
            port=8080,
            app_type="web",
            requested_services=[
                RequestedServiceSpec(service_type="postgres"),
                RequestedServiceSpec(service_type="redis"),
                RequestedServiceSpec(service_type="rabbitmq"),
            ],
        )
        assert len(app.requested_services) == 3
        types = [s.service_type for s in app.requested_services]
        assert "postgres" in types
        assert "redis" in types
        assert "rabbitmq" in types
