apiVersion: v1
kind: ConfigMap
metadata:
  name: iyziops-ui-config
  namespace: haven-system
data:
  NEXTAUTH_URL: "https://iyziops.com"
  NEXT_PUBLIC_API_URL: "https://api.iyziops.com"
  KEYCLOAK_URL: "https://keycloak.iyziops.com"
  KEYCLOAK_REALM: "haven"
  KEYCLOAK_ISSUER: "https://keycloak.iyziops.com/realms/haven"
  NEXT_PUBLIC_LB_IP: "46.225.42.2"
