apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haven-mysql.labels" . | nindent 4 }}
spec:
  crVersion: "1.15.0"
  allowUnsafeConfigurations: {{ .Values.mysql.allowUnsafeConfigurations }}
  pxc:
    size: {{ .Values.mysql.instances }}
    image: percona/percona-xtradb-cluster:{{ .Values.mysql.version }}
    resources:
      requests:
        cpu: {{ .Values.mysql.resources.requests.cpu }}
        memory: {{ .Values.mysql.resources.requests.memory }}
      limits:
        cpu: {{ .Values.mysql.resources.limits.cpu }}
        memory: {{ .Values.mysql.resources.limits.memory }}
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: {{ .Values.mysql.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
    affinity:
      advanced:
        tolerations:
          - operator: "Exists"
  haproxy:
    enabled: {{ .Values.haproxy.enabled }}
    size: {{ include "haven-mysql.haproxy-size" . }}
    image: {{ .Values.haproxy.image }}
    tolerations:
      - operator: "Exists"
