apiVersion: v1
kind: Service
metadata:
  name: haven-ui
  namespace: haven-system
  labels:
    app: haven-ui
    haven.io/component: ui
spec:
  selector:
    app: haven-ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
