# ArgoCD
server:
  extraArgs:
    - --insecure
  replicas: 1
controller:
  replicas: 1
repoServer:
  replicas: 1
redis:
  enabled: true
dex:
  enabled: false
configs:
  cm:
    url: "https://${argocd_host}"
    application.instanceLabelKey: argocd.argoproj.io/instance
  params:
    server.insecure: true
global:
  tolerations:
    - operator: "Exists"
