# Harbor Registry
expose:
  type: clusterIP
  tls:
    enabled: false
externalURL: http://${harbor_host}
harborAdminPassword: "${admin_password}"
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: longhorn
      size: ${registry_storage_size}
    database:
      storageClass: longhorn
      size: 5Gi
    redis:
      storageClass: longhorn
      size: 2Gi
    jobservice:
      jobLog:
        storageClass: longhorn
        size: 2Gi
trivy:
  enabled: true
tolerations:
  - operator: "Exists"
