# KeycloakX (codecentric chart)
image:
  repository: quay.io/keycloak/keycloak
  tag: "26.1"
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--hostname=${keycloak_host}"
  - "--hostname-strict=false"
  - "--http-enabled=true"
  - "--proxy-headers=xforwarded"
  - "--db=postgres"
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "${admin_password}"
  - name: KC_DB_URL_HOST
    valueFrom:
      secretKeyRef:
        name: ${db_secret_name}
        key: host
  - name: KC_DB_URL_PORT
    valueFrom:
      secretKeyRef:
        name: ${db_secret_name}
        key: port
  - name: KC_DB_URL_DATABASE
    valueFrom:
      secretKeyRef:
        name: ${db_secret_name}
        key: dbname
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: ${db_secret_name}
        key: username
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ${db_secret_name}
        key: password
replicas: 1
http:
  relativePath: "/"
service:
  type: ClusterIP
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    memory: 1Gi
tolerations:
  - operator: "Exists"
