apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haven-rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  resources:
    requests:
      cpu: {{ .Values.rabbitmq.resources.requests.cpu }}
      memory: {{ .Values.rabbitmq.resources.requests.memory }}
    limits:
      cpu: {{ .Values.rabbitmq.resources.limits.cpu }}
      memory: {{ .Values.rabbitmq.resources.limits.memory }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.storageClass }}
    storage: {{ .Values.rabbitmq.storage }}
  tolerations:
    - operator: "Exists"
