apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haven-redis.labels" . | nindent 4 }}
spec:
  kubernetesConfig:
    image: {{ .Values.redis.image }}
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: {{ .Values.redis.resources.requests.cpu }}
        memory: {{ .Values.redis.resources.requests.memory }}
      limits:
        cpu: {{ .Values.redis.resources.limits.cpu }}
        memory: {{ .Values.redis.resources.limits.memory }}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.redis.storageClass }}
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
  tolerations:
    - operator: "Exists"
