apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haven-pg.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgres.version }}
  storage:
    storageClass: {{ .Values.postgres.storageClass }}
    size: {{ .Values.postgres.storage }}
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  resources:
    requests:
      cpu: {{ .Values.postgres.resources.requests.cpu }}
      memory: {{ .Values.postgres.resources.requests.memory }}
    limits:
      cpu: {{ .Values.postgres.resources.limits.cpu }}
      memory: {{ .Values.postgres.resources.limits.memory }}
  bootstrap:
    initdb:
      database: {{ .Values.name | replace "-" "_" }}
      owner: {{ .Values.name | replace "-" "_" }}_user
  affinity:
    tolerations:
      - operator: "Exists"
  {{- if .Values.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: "s3://{{ .Values.backup.bucket }}/{{ .Values.name }}"
      s3Credentials:
        accessKeyId:
          name: minio-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "{{ .Values.backup.retentionDays }}d"
  {{- end }}
