{#
  Jinja2 template: ArgoCD ApplicationSet for a single tenant's managed services.

  Variables:
    tenant_slug       — e.g. "gemeente-utrecht"
    repo_url          — e.g. "https://github.com/NimbusProTch/InfraForge-Haven.git"
    target_revision   — e.g. "main" or "feature/platform-v2"
    chart_path        — path to the haven-managed-service Helm chart,
                        e.g. "charts/haven-managed-service"
    gitops_prefix     — root prefix in the repo, default "gitops"

  Generated by: platform/templates/tenant-appset-generator.py

  Naming convention:
    ApplicationSet name: svcset-{{ tenant_slug }}
    Application name:    svc-{{ tenant_slug }}-<service-name>
    Destination NS:      tenant-{{ tenant_slug }}
#}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: svcset-{{ tenant_slug }}
  namespace: argocd
  labels:
    haven.io/managed: "true"
    haven.io/tenant: "{{ tenant_slug }}"
    haven.io/type: "tenant-services"
  annotations:
    haven.io/generated-by: "tenant-appset-generator"
    haven.io/tenant-slug: "{{ tenant_slug }}"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ repo_url }}
        revision: {{ target_revision }}
        directories:
          # Match every service directory: gitops/tenants/{slug}/services/{service-name}
          - path: "{{ gitops_prefix }}/tenants/{{ tenant_slug }}/services/*"
  template:
    metadata:
      # path.segments: [0]=gitops [1]=tenants [2]=tenant_slug [3]=services [4]=service-name
      name: "svc-{{ tenant_slug }}-{% raw %}{{ index .path.segments 4 }}{% endraw %}"
      namespace: argocd
      labels:
        haven.io/managed: "true"
        haven.io/tenant: "{{ tenant_slug }}"
        haven.io/service: "{% raw %}{{ index .path.segments 4 }}{% endraw %}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: {{ repo_url }}
        targetRevision: {{ target_revision }}
        path: "{{ chart_path }}"
        helm:
          valueFiles:
            - "/{% raw %}{{ .path.path }}{% endraw %}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "tenant-{{ tenant_slug }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
