{#
  Jinja2 template: ArgoCD ApplicationSet for a single tenant's apps.

  Variables:
    tenant_slug       — e.g. "gemeente-utrecht"
    repo_url          — e.g. "https://github.com/NimbusProTch/InfraForge-Haven.git"
    target_revision   — e.g. "main" or "feature/platform-v2"
    chart_path        — path to the haven-app Helm chart, e.g. "charts/haven-app"
    gitops_prefix     — root prefix in the repo, default "gitops"

  Generated by: platform/templates/tenant-appset-generator.py
  Applied via:  kubectl apply -f <rendered>.yaml -n argocd
                (or committed to platform/argocd/applicationsets/ and synced by app-of-apps)

  Naming convention:
    ApplicationSet name: appset-{{ tenant_slug }}
    Application name:    {{ tenant_slug }}-<app-slug>
    Destination NS:      tenant-{{ tenant_slug }}
#}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-{{ tenant_slug }}
  namespace: argocd
  labels:
    haven.io/managed: "true"
    haven.io/tenant: "{{ tenant_slug }}"
    haven.io/type: "tenant-apps"
  annotations:
    haven.io/generated-by: "tenant-appset-generator"
    haven.io/tenant-slug: "{{ tenant_slug }}"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ repo_url }}
        revision: {{ target_revision }}
        directories:
          # Match every app directory under this tenant
          - path: "{{ gitops_prefix }}/tenants/{{ tenant_slug }}/*"
          # Exclude the services subdirectory — handled by service-applicationset
          - path: "{{ gitops_prefix }}/tenants/{{ tenant_slug }}/services"
            exclude: true
          - path: "{{ gitops_prefix }}/tenants/{{ tenant_slug }}/services/*"
            exclude: true
  template:
    metadata:
      # path.segments: [0]=gitops [1]=tenants [2]=tenant_slug [3]=app-slug
      name: "{{ tenant_slug }}-{% raw %}{{ index .path.segments 3 }}{% endraw %}"
      namespace: argocd
      labels:
        haven.io/managed: "true"
        haven.io/tenant: "{{ tenant_slug }}"
        haven.io/app: "{% raw %}{{ index .path.segments 3 }}{% endraw %}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: {{ repo_url }}
        targetRevision: {{ target_revision }}
        path: "{{ chart_path }}"
        helm:
          valueFiles:
            - "/{% raw %}{{ .path.path }}{% endraw %}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "tenant-{{ tenant_slug }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
