{{- if eq .Values.serviceType "mongodb" }}
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "managed-service.labels" . | nindent 4 }}
spec:
  crVersion: "1.17.0"
  image: percona/percona-server-mongodb:{{ .Values.mongodb.version }}
  allowUnsafeConfigurations: {{ if eq .Values.tier "dev" }}true{{ else }}false{{ end }}
  replsets:
    - name: rs0
      size: {{ include "managed-service.instances" . }}
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          memory: "1Gi"
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: {{ .Values.mongodb.storageClass }}
          resources:
            requests:
              storage: {{ include "managed-service.storage" . }}
      nonvoting:
        enabled: false
      affinity:
        advanced:
          tolerations:
            - operator: "Exists"
  mongos:
    size: {{ if eq .Values.tier "prod" }}2{{ else }}1{{ end }}
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
    tolerations:
      - operator: "Exists"
  sharding:
    enabled: false
{{- end }}
