{{- if eq .Values.serviceType "mysql" }}
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "managed-service.labels" . | nindent 4 }}
spec:
  crVersion: "1.15.0"
  allowUnsafeConfigurations: {{ if eq .Values.tier "dev" }}true{{ else }}false{{ end }}
  pxc:
    size: {{ include "managed-service.instances" . }}
    image: percona/percona-xtradb-cluster:{{ .Values.mysql.version }}
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        memory: "1Gi"
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: {{ .Values.mysql.storageClass }}
        resources:
          requests:
            storage: {{ include "managed-service.storage" . }}
    affinity:
      advanced:
        tolerations:
          - operator: "Exists"
  haproxy:
    enabled: true
    size: {{ if eq .Values.tier "prod" }}2{{ else }}1{{ end }}
    image: percona/haproxy:2.8.5
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
    tolerations:
      - operator: "Exists"
{{- end }}
