{{- if eq .Values.serviceType "rabbitmq" }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "managed-service.labels" . | nindent 4 }}
spec:
  replicas: {{ if eq .Values.tier "prod" }}3{{ else }}1{{ end }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.storageClass }}
    storage: {{ if eq .Values.tier "prod" }}10Gi{{ else }}5Gi{{ end }}
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
  rabbitmq:
    additionalConfig: |
      default_user_tags.administrator = true
  override:
    statefulSet:
      spec:
        template:
          spec:
            tolerations:
              - operator: "Exists"
{{- end }}
