{{- if eq .Values.serviceType "redis" }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "managed-service.labels" . | nindent 4 }}
spec:
  kubernetesConfig:
    image: {{ .Values.redis.image }}
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.redis.storageClass }}
        resources:
          requests:
            storage: {{ include "managed-service.storage" . }}
  tolerations:
    - operator: "Exists"
{{- end }}
