apiVersion: v1
kind: ConfigMap
metadata:
  name: haven-api-config
  namespace: haven-system
data:
  KEYCLOAK_URL: "https://keycloak.46.225.42.2.sslip.io"
  KEYCLOAK_REALM: "haven"
  HARBOR_URL: "http://harbor.46.225.42.2.sslip.io"
  HARBOR_PROJECT: "library"
  LB_IP: "46.225.42.2"
  BUILD_NAMESPACE: "haven-builds"
  BUILDKIT_ADDR: "tcp://buildkitd.haven-builds.svc.cluster.local:1234"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:3001,http://app.46.225.42.2.sslip.io,https://app.46.225.42.2.sslip.io"
  GITHUB_REDIRECT_URI: "http://app.46.225.42.2.sslip.io/github/callback"
  ARGOCD_URL: "http://argocd-server.argocd.svc.cluster.local:80"
  DEBUG: "false"
