#!/usr/bin/env bash
# Fetch the RKE2 kubeconfig from the first master and pin it under
# /tmp/iyziops-kubeconfig so `make haven`, `make deploy-check`, kubectl,
# etc. all pick it up automatically.
#
# Cluster nodes have no public IPv4 (Haven privatenetworking), so we
# tunnel the SCP through the NAT box via OpenSSH ProxyJump. The NAT box
# and master share the same SSH key (generated by tofu and written to
# logs/iyziops-prod-ssh.pem).
#
# After download, the server URL is rewritten from 127.0.0.1 → API LB
# public IPv4 so out-of-cluster kubectl can connect.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFRA_DIR="$REPO_ROOT/infrastructure/environments/prod"
KEY="$REPO_ROOT/logs/iyziops-prod-ssh.pem"
OUT="/tmp/iyziops-kubeconfig"

# Load sensitive Keychain credentials (Hetzner + S3 state backend)
# so `tofu output` can talk to the remote state bucket.
if [[ -z "${AWS_ACCESS_KEY_ID:-}" ]]; then
  if declare -F iyziops-env >/dev/null 2>&1; then
    iyziops-env >/dev/null
  elif [[ -f "$HOME/.zshrc" ]]; then
    # shellcheck disable=SC1091
    source "$HOME/.zshrc" >/dev/null 2>&1 || true
    if declare -F iyziops-env >/dev/null 2>&1; then
      iyziops-env >/dev/null
    fi
  fi
fi

if [[ ! -f "$KEY" ]]; then
  echo "ERROR: SSH key not found at $KEY — run 'make infra-apply' first." >&2
  exit 1
fi
chmod 600 "$KEY"

echo "==> reading tofu outputs"
cd "$INFRA_DIR"
NAT_IP=$(tofu output -raw nat_public_ipv4)
LB_IP=$(tofu output -raw load_balancer_api_ipv4)
MASTER_PRIVATE_IP=$(tofu output -raw first_master_private_ipv4 2>/dev/null || echo "10.10.1.10")

echo "==> NAT  public IPv4: $NAT_IP"
echo "==> API  LB  IPv4:    $LB_IP"
echo "==> master private:   $MASTER_PRIVATE_IP"

SSH_OPTS=(-i "$KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR)

# ProxyCommand nests another ssh invocation that needs its own flags;
# ProxyJump does not propagate parent options, so we build the nested
# command explicitly.
PROXY_CMD="ssh -i $KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -W %h:%p root@${NAT_IP}"

echo "==> fetching rke2.yaml via NAT bastion"
scp "${SSH_OPTS[@]}" \
    -o "ProxyCommand=${PROXY_CMD}" \
    "root@${MASTER_PRIVATE_IP}:/etc/rancher/rke2/rke2.yaml" \
    "$OUT"

echo "==> rewriting server URL → https://${LB_IP}:6443"
# BSD/macOS sed uses -i '' — Linux sed uses -i. Detect both.
if sed --version >/dev/null 2>&1; then
  sed -i "s|https://127.0.0.1:6443|https://${LB_IP}:6443|" "$OUT"
else
  sed -i '' "s|https://127.0.0.1:6443|https://${LB_IP}:6443|" "$OUT"
fi
chmod 600 "$OUT"

echo "==> kubeconfig ready at $OUT"
echo "    export KUBECONFIG=$OUT"
