apiVersion: v2
name: haven-rabbitmq
description: Haven Platform managed RabbitMQ chart (RabbitMQ Cluster Operator)
type: application
version: 0.1.0
appVersion: "3.13"
keywords:
  - haven
  - rabbitmq
  - messaging
  - queue
maintainers:
  - name: Haven Platform Team
