apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haven-ui
  namespace: argocd
  labels:
    haven.io/component: ui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NimbusProTch/InfraForge-Haven
    targetRevision: feature/platform-v2
    path: platform/manifests/haven-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: haven-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
