apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haven-api
  namespace: argocd
  labels:
    haven.io/component: api
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NimbusProTch/InfraForge-Haven
    targetRevision: feature/platform-v2
    path: platform/manifests/haven-api
  destination:
    server: https://kubernetes.default.svc
    namespace: haven-system
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/parentRefs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
